defaultContentLanguage = "ja"
disqusShortname = "tocky-net"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[permalinks]
    posts = "/:year/:month/:slugorfilename/"


[languages]
    [languages.en]
        [languages.en.params]
            displayName = "ğŸ‡ºğŸ‡¸"
            description = "Technology, software, development, cloud, and everything else I'm interested in"
    [languages.ja]
        [languages.ja.params]
            displayName = "ğŸ‡¯ğŸ‡µ"
            description = "ãƒ†ã‚¯ãƒãƒ­ã‚¸ãƒ¼ã€ã‚½ãƒ•ãƒˆã‚¦ã‚§ã‚¢ã€é–‹ç™ºã€ã‚¯ãƒ©ã‚¦ãƒ‰ãªã©ç§ãŒèˆˆå‘³ã®ã‚ã‚‹ã“ã¨ã™ã¹ã¦"
