languageCode = "ja"
languageName = "æ—¥æœ¬èª"
displayName = "ğŸ‡¯ğŸ‡µ"
title = "tocky.net"
description = "ãƒ†ã‚¯ãƒãƒ­ã‚¸ãƒ¼ã€ã‚½ãƒ•ãƒˆã‚¦ã‚§ã‚¢ã€é–‹ç™ºã€ã‚¯ãƒ©ã‚¦ãƒ‰ãªã©ç§ãŒèˆˆå‘³ã®ã‚ã‚‹ã“ã¨ã™ã¹ã¦"
copyright = "&copy; tocky.net"

[author]
name = "Shin Tokiwa"
image = "images/author.jpg"
headline = "A developer who love technologies"
bio = "A little bit about me"
links = [
    # { twitter = "https://twitter.com/tocky816" },
    # { instagram = "https://instagram.com/tocky" },
    # { facebook = "https://fb.com/tocky" },
    # { linkedin = "https://www.linkedin.com/in/tocky/" },
    { github = "https://github.com/tocky" },
]
